name: banana_talk
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_webrtc: ^1.2.1
  web_socket_channel: ^3.0.3
  cupertino_icons: ^1.0.2
  permission_handler: ^12.0.1
  google_sign_in: ^7.2.0
  flutter_secure_storage: ^10.0.0
  jwt_decoder: ^2.0.1

flutter:
  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "assets/icon_background.png"
  adaptive_icon_foreground: "assets/icon_foreground.png"
  macos:
    generate: true
    image_path: "assets/icon.png"
